#!/bin/bash
alias aliases="vim ~/.aliases"

# Folders
alias p="cd ~/Projects"

# Vim
alias vim="nvim"
alias vi="vim"
alias v="vim"

# History
alias h="history"

# Navigation
# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag="--color"
else # OS X `ls`
  colorflag="-G"
fi

# ls with permanent color output
alias ls="command ls ${colorflag}"

# Android Emulator
# Fix : https://stackoverflow.com/questions/42554337/cannot-launch-avd-in-emulatorqt-library-not-found
# alias emulator="/usr/local/Caskroom/android-sdk/4333796/tools/emulator"
